name: "Unit Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies & Test
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go test -parallel 4 -v encrypt.go encrypt_test.go